-- begin CESDV_ORDER
alter table CESDV_ORDER add constraint FK_CESDV_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CESDV_CUSTOMER(ID)^
create index IDX_CESDV_ORDER_ON_CUSTOMER on CESDV_ORDER (CUSTOMER_ID)^
-- end CESDV_ORDER
-- begin CESDV_INVOICE
alter table CESDV_INVOICE add constraint FK_CESDV_INVOICE_ON_CUSTOMER foreign key (CUSTOMER_ID) references CESDV_CUSTOMER(ID)^
create index IDX_CESDV_INVOICE_ON_CUSTOMER on CESDV_INVOICE (CUSTOMER_ID)^
-- end CESDV_INVOICE
